[features]
seeds = false
skip-lint = false

[programs.localnet]
auddshield = "5HQgDy3tkLkmT6JeFYem9dCiS3ye9CpHznoVtNhTsifM"

[programs.devnet]
auddshield = "5HQgDy3tkLkmT6JeFYem9dCiS3ye9CpHznoVtNhTsifM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
